### ISSUE TITLE
Does not configure on Ubuntu 18.04

### ISSUE THREAD

**Issue by mmaurus** [rock-planning/planning-orogen-motion_planning_libraries#2]
Hi.
This rock task does not configure on Ubuntu 18.04 with the following errors:
* ignoring /std/pair</double,/double>, it has private base classes
* ignoring /motionplanninglibraries/Config since its field mFootprintRadiusMinMax is of the ignored type /std/pair</double,/double>

Looks like the typelib can't figure out std::pair.

Any solutions?

**Comment by skasperski** [comment]
Can you verify that this is solved by https://github.com/rock-planning/planning-motion_planning_libraries/pull/16 ?

**Comment by mmaurus** [comment]
Yes I can confirm that. Now, it fails when linking with **undefined reference to 'RTT::internal::DataSource<bool>::getType() const'** and **undefined reference to 'RTT::internal::DataSource<bool>::getTypeName() const'**

**Comment by skasperski** [comment]
I just had the same issue and it was "solved" for me by removing the Task "Test" from the orogen-file. What does this test? Does someone know if it is required?

@mmaurus Did you find another solution?

**Comment by mmaurus** [comment]
I still have this problem with rock debian package 20.01. Not with 19.06!

**Comment by 2maz** [comment]
@mmaurus as we figured out wIth master-20.01 this linking issue exists, when using return type bool for an operation. I am afraid, however, this will only be fixed in the upcoming release, which will have a clean way of linking and using includes based on separate package prefixes -  anticipating EO June for bionic/amd64 ready for testing.

**Comment by mmaurus** [comment]
@2maz unfortunately, this issue is not fixed with the new debian packages 20.06

**Comment by mmaurus** [comment]
One solution/workaround would be to change the operation "generateEscapeTrajectory" to returning an int instead of a bool
